const AIRPORTS: Record<string, string> = {
  sydney: "SYD",
  melbourne: "MEL",
  brisbane: "BNE",
  perth: "PER",
  adelaide: "ADL",
  "gold coast": "OOL",
  canberra: "CBR",
  hobart: "HBA",
  darwin: "DRW",
  cairns: "CNS",
  auckland: "AKL",
  wellington: "WLG",
  christchurch: "CHC",
  queenstown: "ZQN",

  tokyo: "NRT",
  osaka: "KIX",
  kyoto: "KIX",
  nagoya: "NGO",
  sapporo: "CTS",
  fukuoka: "FUK",
  okinawa: "OKA",
  seoul: "ICN",
  busan: "PUS",
  beijing: "PEK",
  shanghai: "PVG",
  guangzhou: "CAN",
  shenzhen: "SZX",
  chengdu: "CTU",
  "hong kong": "HKG",
  hongkong: "HKG",
  taipei: "TPE",
  singapore: "SIN",
  bangkok: "BKK",
  "chiang mai": "CNX",
  phuket: "HKT",
  "kuala lumpur": "KUL",
  jakarta: "CGK",
  bali: "DPS",
  denpasar: "DPS",
  manila: "MNL",
  hanoi: "HAN",
  "ho chi minh city": "SGN",
  saigon: "SGN",
  "siem reap": "SAI",

  delhi: "DEL",
  "new delhi": "DEL",
  mumbai: "BOM",
  bengaluru: "BLR",
  bangalore: "BLR",
  dubai: "DXB",
  "abu dhabi": "AUH",
  doha: "DOH",
  istanbul: "IST",

  london: "LHR",
  paris: "CDG",
  amsterdam: "AMS",
  frankfurt: "FRA",
  munich: "MUC",
  berlin: "BER",
  zurich: "ZRH",
  vienna: "VIE",
  prague: "PRG",
  rome: "FCO",
  milan: "MXP",
  venice: "VCE",
  barcelona: "BCN",
  madrid: "MAD",
  lisbon: "LIS",
  porto: "OPO",
  dublin: "DUB",
  edinburgh: "EDI",
  copenhagen: "CPH",
  stockholm: "ARN",
  oslo: "OSL",
  helsinki: "HEL",
  reykjavik: "KEF",
  athens: "ATH",
  budapest: "BUD",
  warsaw: "WAW",

  "new york": "JFK",
  nyc: "JFK",
  "los angeles": "LAX",
  "san francisco": "SFO",
  seattle: "SEA",
  chicago: "ORD",
  boston: "BOS",
  "washington dc": "IAD",
  miami: "MIA",
  "las vegas": "LAS",
  honolulu: "HNL",
  toronto: "YYZ",
  vancouver: "YVR",
  montreal: "YUL",
  "mexico city": "MEX",
  "sao paulo": "GRU",
  "rio de janeiro": "GIG",
  "buenos aires": "EZE",
  lima: "LIM",
  santiago: "SCL",

  cairo: "CAI",
  "cape town": "CPT",
  johannesburg: "JNB",
  nairobi: "NBO",
  marrakech: "RAK",
  "tel aviv": "TLV",
};

const PASSTHROUGH = /^[A-Z]{3}$|^\/[mg]\//;

export function airportCodeFor(city: string): string | undefined {
  const trimmed = city.trim();
  if (PASSTHROUGH.test(trimmed)) return trimmed;

  const key = trimmed
    .toLowerCase()
    .replace(/[.,'’]/g, "")
    .replace(/[-_]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
  return AIRPORTS[key];
}

export const knownAirportCities = () => Object.keys(AIRPORTS).sort();
